# Generated by Django 5.0.6 on 2024-06-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('customerMobNo', models.BigIntegerField()),
                ('customerAddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNo', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('problem', models.TextField()),
                ('remark', models.TextField()),
                ('inwardDate', models.DateTimeField(auto_now_add=True)),
                ('commitmentDate', models.DateField()),
                ('productStatus', models.CharField(max_length=30)),
                ('productChecked', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_inward', to='mainapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(editable=False, max_length=7, unique=True)),
                ('component', models.CharField(max_length=100, null=True)),
                ('serviceRemark', models.CharField(max_length=100)),
                ('serviceStatus', models.CharField(max_length=30)),
                ('serviceCost', models.FloatField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='mainapp.productinward')),
            ],
        ),
    ]
