# Generated by Django 5.0.6 on 2024-06-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_customer_productinward_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplName', models.CharField(max_length=100)),
                ('empEmail', models.EmailField(max_length=254)),
                ('empMobNo', models.BigIntegerField()),
                ('empDOB', models.DateField()),
                ('salary', models.FloatField()),
                ('position', models.CharField(choices=[('Laptop Technician', 'Laptop Technician'), ('Computer Technician', 'Computer Technician'), ('Chip-level Technician', 'Chip-level Technician'), ('Manager', 'Manager'), ('HR', 'HR'), ('Other Staff', 'Other Staff')], max_length=30)),
                ('empTerms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerSatisfaction', models.CharField(blank=True, choices=[('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Not Satisfied', 'Not Satisfied')], max_length=20, null=True)),
                ('deliveredOnTime', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Customer', to='mainapp.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='mainapp.productinward')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='mainapp.service')),
            ],
        ),
    ]
