# Generated by Django 5.0.6 on 2024-06-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_emplname_team_empname'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceTechnician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceTechnician', to='mainapp.team'),
        ),
    ]
