# Generated by Django 5.0.6 on 2024-06-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_service_servicetechnician'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='mainapp.team'),
        ),
    ]
