# Generated by Django 5.0.6 on 2024-06-29 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delivery_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deliveryDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
