# Generated by Django 5.0.6 on 2025-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_team_user_alter_user_terms_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceRemark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceStatus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
