# Generated by Django 5.0.6 on 2025-07-08 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 8, 6, 30, 44, 80635, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_name',
            field=models.CharField(max_length=20),
        ),
    ]
