# Generated by Django 5.0.6 on 2025-07-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_tax_date_added_alter_tax_tax_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_product', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Monitor Part', 'Monitor Part'), ('Keyboard', 'Keyboard'), ('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('Hard Disk', 'Hard Disk'), ('SSD', 'SSD'), ('Battery', 'Battery'), ('Charger', 'Charger'), ('Screen', 'Screen'), ('Mouse', 'Mouse'), ('Printer', 'Printer'), ('Other', 'Other')], max_length=100)),
                ('rate_of_purchase', models.FloatField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
