# Generated by Django 5.0.6 on 2025-07-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='value',
            field=models.CharField(blank=True, help_text='Values like 16Gb, 500SSD', max_length=100, null=True),
        ),
    ]
