# Generated by Django 5.0.6 on 2025-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_inventory_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='component_inventory',
            field=models.ManyToManyField(to='mainapp.inventory'),
        ),
    ]
